<a href="https://colab.research.google.com/github/JustinCamay-prog/Lab-Activities/blob/main/Activity_7_Task_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [7]:
import numpy as np

A1 = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
A2 = np.array([[5, 6, 7], [8, 9, 1], [2, 3, 4]])
A3 = np.array([[9, 8, 7], [6, 5, 4], [3, 2, 1]])
A4 = np.identity(3)
A5 = np.zeros([3,3])

print("Shapes of Matrices")
print(A1.shape)
print(A2.shape)
print(A3.shape)
print(A4.shape)
print(A5.shape)
print('\n')

def Commutative_Property(M1, M2):
    A1A2 = np.dot(M1, M2)
    A2A1 = np.dot(M2, M1)
    print("Commutative Property")
    print("A1A2" '\n', A1A2)
    print("A2A1" '\n', A2A1)
    print('\n')

def Associative_Property(M1, M2, M3):
    A2A3 = np.dot(M2, M3)
    A2A3A1 = np.dot(M1, A2A3)
    A1A2 = np.dot(M1, M2)
    A1A2A3 = np.dot(A1A2, M3)
    print("Associative Property")
    print("A1A2A3" '\n', A1A2A3)
    print("A2A3A1" '\n', A2A3A1)
    print('\n')

def Distributive_Property(M1, M2, M3):
    A2A3 = np.add(M2, M3)
    A1A2A3 = np.dot(M1, A2A3)
    A1A2 = np.dot(M1, M2)
    A1A3 = np.dot(M1, M3)
    print("Distributive Property")
    print("A1A2A3")
    print(A1A2A3, '\n=\n', A1A2 + A1A3)
    print('\n')

    A2A3A1 = np.dot(A2, M1)
    A2A1 = np.dot(M2, M1)
    A3A1 = np.dot(M3, M1)
    print("A2A3A1")
    print(A2A3A1, '\n=\n', A2A1 + A3A1)
    print('\n')


def Identity_Property(M1, MIP):
    print("Identity Property")
    Identity = np.dot(M1, MIP)
    print(Identity, '\n=\n', M1)
    print('\n')


def Zero_Property(M1, Zero):
    print("Zero Property")
    Z = np.dot(M1, Zero)
    print(Z, '\n=\n', Zero)
    print('\n')


Commutative_Property(A1, A2)
Associative_Property(A1, A2, A3)
Distributive_Property(A1, A2, A3)
Identity_Property(A1, A4)
Zero_Property(A1, A5)

Shapes of Matrices
(3, 3)
(3, 3)
(3, 3)
(3, 3)
(3, 3)


Commutative Property
A1A2
 [[ 27  33  21]
 [ 72  87  57]
 [117 141  93]]
A2A1
 [[ 78  96 114]
 [ 51  69  87]
 [ 42  51  60]]


Associative Property
A1A2A3
 [[ 504  423  342]
 [1341 1125  909]
 [2178 1827 1476]]
A2A3A1
 [[ 504  423  342]
 [1341 1125  909]
 [2178 1827 1476]]


Distributive Property
A1A2A3
[[ 57  57  39]
 [156 156 111]
 [255 255 183]] 
=
 [[ 57  57  39]
 [156 156 111]
 [255 255 183]]


A2A3A1
[[ 78  96 114]
 [ 51  69  87]
 [ 42  51  60]] 
=
 [[168 210 252]
 [105 138 171]
 [ 60  75  90]]


Identity Property
[[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]] 
=
 [[1 2 3]
 [4 5 6]
 [7 8 9]]


Zero Property
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]] 
=
 [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


